POST http://localhost:8082/api/pet
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhZG1pbiIsImV4cCI6MTY3MTQ0MTE3Nn0.D4WN1tILaki2fDcFgX343xN8Y9CBdZogTVD__Cn-gWw

{
    "name": "ally",
    "type": "dog",
    "description": "this is her dog",
    "age": "26"
}