GET http://localhost:8082/api/owner/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhZG1pbiIsImV4cCI6MTY3MDg0NzQ0NH0.bPQiYVTv9K-CR3wlcDOOn59TCCNe1SIQ4FvpgDaP8do
