GET http://localhost:8082/api/owner/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhZG1pbiIsImV4cCI6MTY3MDg1MjE1NX0.M0Hqc6FlCtxR-7Usi9qPXWGA4vvNWHMRQrpW8Oy7UZk
